// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwwxkkkzkwiftbekezvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3d3hra2t6a3dpZnRiZWtlenZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzI3OTcsImV4cCI6MjA2NTY0ODc5N30.oHPqmgqaQf2aN4jLPefMWk03DfKjSUzUplRx3RZPPuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);